env:
  browser: true
  es2021: true
  "jest/globals": true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - jest
  - react
rules: {
  "linebreak-style": 0,
  "react/react-in-jsx-scope": 0
}
root: true
